import { AlertCircle, FileText } from "lucide-react";
import { useTranslation } from "react-i18next";
import Layout from "./layout/Layout";

export default function TranslatedPolicyPage({ namespace }) {
  const { t } = useTranslation();
  const cards=t(`${namespace}.cards`,{returnObjects:true});
  const sections=t(`${namespace}.sections`,{returnObjects:true});
  return <Layout><section className="border-b border-gray-200 bg-gray-50 dark:border-zinc-800 dark:bg-zinc-950"><div className="mx-auto max-w-7xl px-6 py-20 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-black text-white dark:bg-white dark:text-black"><FileText size={26}/></div><p className="mt-6 text-sm font-black uppercase tracking-[.25em] text-gray-500">{t("policyCommon.legal")}</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">{t(`${namespace}.title`)}</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-gray-500">{t(`${namespace}.intro`)}</p><p className="mt-4 text-sm font-semibold text-gray-500">{t("policyCommon.updated")}</p></div></section><section className="mx-auto max-w-7xl px-6 py-16"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><article key={c.title} className="rounded-3xl border border-gray-200 p-6 dark:border-zinc-800"><h2 className="text-xl font-black">{c.title}</h2><p className="mt-3 text-sm leading-6 text-gray-500">{c.text}</p></article>)}</div><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_320px]"><article className="rounded-[32px] border border-gray-200 p-6 dark:border-zinc-800 sm:p-9"><div className="space-y-10">{sections.map(s=><section key={s.title}><h2 className="text-2xl font-black">{s.title}</h2><div className="mt-4 space-y-3">{s.content.map(x=><p key={x} className="leading-7 text-gray-600 dark:text-gray-400">{x}</p>)}</div></section>)}</div></article><aside className="h-fit rounded-3xl bg-black p-6 text-white lg:sticky lg:top-24 dark:bg-white dark:text-black"><AlertCircle size={25}/><h2 className="mt-4 text-xl font-black">{t("policyCommon.contactTitle")}</h2><p className="mt-3 leading-7 text-gray-300 dark:text-gray-600">{t("policyCommon.contactText")}</p></aside></div></section></Layout>;
}
