import { useState } from "react";
import { Mail, MapPin, MessageCircle, Phone, Send } from "lucide-react";
import toast from "react-hot-toast";
import { useTranslation } from "react-i18next";
import Layout from "../components/layout/Layout";
import { supabase } from "../lib/supabase";

export default function Contact() {
  const { t } = useTranslation();
  const [form,setForm]=useState({name:"",email:"",subject:"",message:""});
  const [loading,setLoading]=useState(false);
  const faqs=t("contact.faqs",{returnObjects:true});
  const change=(e)=>setForm(v=>({...v,[e.target.name]:e.target.value}));
  const submit=async(e)=>{ e.preventDefault(); if(Object.values(form).some(v=>!v.trim())){toast.error(t("contact.required"));return;} try{setLoading(true); const {error}=await supabase.from("contact_messages").insert({name:form.name.trim(),email:form.email.trim(),subject:form.subject.trim(),message:form.message.trim()}); if(error)throw error; toast.success(t("contact.sent")); setForm({name:"",email:"",subject:"",message:""});}catch(error){console.error("Contact form error:",error);toast.error(t("contact.failed"));}finally{setLoading(false);}};
  return <Layout><section className="mx-auto max-w-7xl px-6 py-16 sm:py-20"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[.22em] text-gray-400">{t("contact.eyebrow")}</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">{t("contact.title")}</h1><p className="mt-5 text-lg leading-8 text-gray-500">{t("contact.intro")}</p></div><div className="mt-12 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4">{[[Mail,t("contact.email"),"veromek00@proton.me"],[Phone,t("contact.whatsapp"),"+34 610 982 845"],[MapPin,t("contact.location"),"Valencia, Spain"],[MessageCircle,t("contact.hours"),t("contact.hoursValue")]].map(([Icon,title,text])=><article key={title} className="flex gap-4 rounded-3xl border border-gray-200 p-5 dark:border-zinc-800"><Icon size={22}/><div><h2 className="font-black">{title}</h2><p className="mt-1 text-gray-500">{text}</p></div></article>)}</div><form onSubmit={submit} className="rounded-[32px] border border-gray-200 p-6 dark:border-zinc-800"><h2 className="text-2xl font-black">{t("contact.formTitle")}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input required name="name" value={form.name} onChange={change} placeholder={t("contact.name")} className="rounded-xl border p-4 dark:border-zinc-700 dark:bg-zinc-900"/><input required type="email" name="email" value={form.email} onChange={change} placeholder={t("contact.emailPlaceholder")} className="rounded-xl border p-4 dark:border-zinc-700 dark:bg-zinc-900"/><input required name="subject" value={form.subject} onChange={change} placeholder={t("contact.subject")} className="rounded-xl border p-4 sm:col-span-2 dark:border-zinc-700 dark:bg-zinc-900"/><textarea required rows="6" name="message" value={form.message} onChange={change} placeholder={t("contact.message")} className="rounded-xl border p-4 sm:col-span-2 dark:border-zinc-700 dark:bg-zinc-900"/><button disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-black px-6 py-4 font-black text-white sm:col-span-2 dark:bg-white dark:text-black"><Send size={18}/>{loading?t("contact.sending"):t("contact.send")}</button></div></form></div><div className="mt-16"><h2 className="text-3xl font-black">{t("contact.faqTitle")}</h2><div className="mt-6 divide-y rounded-3xl border px-6 dark:border-zinc-800">{faqs.map(f=><details key={f.q} className="py-5"><summary className="cursor-pointer font-black">{f.q}</summary><p className="mt-3 text-gray-500">{f.a}</p></details>)}</div></div></section></Layout>;
}
